# -*- coding: utf-8 -*-
"""DAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sa1oc9xakRODGEU9sCB8vhTpQuUAeR6a
"""

import numpy as np
#creating arrays
arr=np.array([1,2,3,4,5])
print(arr)
a=np.zeros((3,3),dtype=int)
print(a)
b=np.ones((2,2),dtype=int)
print(b)
#arrange array
arangearr=np.arange(10)
print(arangearr)
#reshaped array
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)
#sliced array
sliced_arr=arr[2:4]
print(sliced_arr)
#addition of arrays
arr2=np.array([1,2,3])
arr1=np.array([6,7,8])
result=arr2+arr1
print(result)
#numpy manipulation vstack func
c=np.vstack(arr2+arr1)
print(c)
c=np.stack(arr2+arr1)
print(c)
#spliting fuctions
arr4=np.array([2,4,6,8,10,11,12])
f=np.split(arr4,3.5)
print(f)
#splitting method 2
arr5=np.array([1,2,3,4,5,6])
e=np.split(arr5,3)
print(e)
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.T
print(b)
#linear algebra with numpy
#seperate 2d 2x2 matrix
g=np.array([[2,5],[4,8]])
p=np.array([[3,6],[1,5]])
j=np.dot(g,p)
print(j)
d=np.linalg.eig(j)
print(d)
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=np.array([[7,8,9],[10,11,12]])
print(b)
#sum of arrays
c=np.sum([a+b])
print(c)
#statistical operations
o=np.array([1,2,3,4,5])
v=np.mean(o)
print(v)
k=np.median(o)
print(k)
l=np.var(o)
print(l)
h=np.std(o)
print(h)