# -*- coding: utf-8 -*-
"""Matplolib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LTaORAFmsUGHcw6FxjzYY6B9IH418pGc
"""

import matplotlib.pyplot as plt
import numpy as np
a=np.array([1,2,3,4,5])
plt.plot(a)