# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/132jXrvAqQtZF0sdzTMCeqYhYqk0RSdcT
"""

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
#create a scatter plot
sns.scatterplot(x="total_bill",y="tip",data=tips)
plt.title("scatter plot of Total bills vs. Tip")
plt.xlabel("Total Bill ($)")
plt.ylabel("Tip ($)")
plt.show()

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
tips=sns.load_dataset("titanic")
print(tips)
#create a scatter plot
sns.scatterplot(x="survived",y="age",data=tips)
plt.title("scatter plot of survived vs. age")
plt.xlabel("Survived")
plt.ylabel("age")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example dataset
iris=sns.load_dataset("iris")
print(iris)
correlation_matrix=iris.corr()
#correlation matrix
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation Heatmap of Iris Dataset")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example dataset
iris=sns.load_dataset("dots")
print(iris)
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation Heatmap of Iris Dataset")
plt.show()

